/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    FileTransform: typeof import('./src/components/FileTransform/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NIcon: typeof import('naive-ui')['NIcon']
    NP: typeof import('naive-ui')['NP']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
  }
}
